OrderSys/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from tastypie.api import Api
from manager.resources import UserResource, ClienteResource, FuncionarioResource, ServicoResource, HistoricoResource

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(ClienteResource())
v1_api.register(FuncionarioResource())
v1_api.register(ServicoResource())
v1_api.register(HistoricoResource())

urlpatterns = [
    # Examples:
    # url(r'^$', 'OrderSys.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
]

manager/urls.py
# __author__ = 'joao'
#
# from django.conf.urls import include, patterns
# from tastypie.api import Api
# from manager.resources import ClienteResource
#
# v1_api = Api(api_name='v1')
# v1_api.register(ClienteResource())
#
# urlpatterns = patterns('',
#   # ...more URLconf bits here...
#   # Then add:
#   (r'^api/', include(v1_api.urls)),
# )

api/models.py
from django.db import models

# Create your models here.

manager/models.py
from django.db import models
from django.utils import timezone

class Cliente(models.Model):
    nome = models.CharField(max_length=200, null=False)
    sobrenome = models.CharField(max_length=200, null=False)
    telefone = models.CharField(max_length=200, null=False)
    email = models.CharField(max_length=200)
    data_cadastro = models.DateTimeField(default=timezone.now, null=False)

    def salvar(self):
        self.data_cadastro = timezone.now()
        self.save()

    def __str__(self):
        return self.nome

    def ident(self):
        ident = str(self.id)
        return ident
    ident.short_description = 'ID'

class Funcionario(models.Model):
    nome = models.CharField(max_length=200, null=False)
    sobrenome = models.CharField(max_length=200, null=False)
    telefone = models.CharField(max_length=200, null=False)
    email = models.CharField(max_length=200)
    data_admissao = models.DateTimeField( default=timezone.now, null=False)
    data_demissao = models.DateTimeField(blank=True, null=True)

    def salvar(self):
        self.data_admissao = timezone.now()
        self.save()

    def __str__(self):
        return self.nome

    def ident(self):
        ident = str(self.id)
        return ident
    ident.short_description = 'ID'


class Servico(models.Model):
    nome = models.CharField(max_length=200, null=False)
    descricao = models.TextField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome

    def ident(self):
        ident = str(self.id)
        return ident
    ident.short_description = 'ID'

class Historico(models.Model):
    cliente = models.ForeignKey(Cliente)
    funcionario = models.ForeignKey(Funcionario)
    servicos = models.ManyToManyField(Servico)
    data_chamado = models.DateTimeField(default=timezone.now, null=False)
    data_realizacao = models.DateTimeField(blank=True, null=True)
    observacao = models.TextField()

    def salvar(self):
        self.data_chamado = timezone.now()
        self.save()

    def ident(self):
        ident = str(self.id)
        return ident
    ident.short_description = 'ID'

    def __str__(self):
        ident = str(self.id)
        return ident

    def valor(self):
        soma = float(0)
        valores = self.servicos.values('valor')
        tam = len(valores)
        x= 0
        for x in range(tam):
            soma = float(soma) + float(self.servicos.values().__getitem__(x).get('valor'))
        #self.valor_total = soma
        return soma

api/views.py
from django.shortcuts import render

# Create your views here.

manager/templates/manager/historico_detail.html
<h1>ID: {{ historico.id }}</h1>
<ul>
    <li>Clinte: {{ historico.cliente }}</li>
    <li>Funcionario: {{ historico.funcionario }}</li>
    <li>Abertura Chamado: {{ historico.data_chamado }}</li>
    <li>Fechamento do chamado: {{ historico.data_realizacao }}</li>
    <li>Valor: {{ historico.valor_total }}</li>
    <li>Observacao: {{ historico.observacao }}</li>
    <b>Servicos:</b>
    {% for servico in historico.servico_set.all %}
        {{ servico.nome }},
    {% endfor %}
</ul>

manager/templates/manager/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'manager/style.css' %}" />

{% if all_historico_list %}
    <ul>
    <h1>ID do historico</h1>
    {% for historico in all_historico_list %}
        <li><a href="{% url 'manager:detail' historico.id %}">{{ historico.id }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nao existe historico disponivel.</p>
{% endif %}
{% load staticfiles %}

manager/templates/manager/results.html
<h1>{{ historico.id }}</h1>

<ul>
{% for servico in historico.servico_set.all %}
    <li>{{ servico.nome }}</li>
{% endfor %}
</ul>

<a href="{% url 'manager:detail' historico.id %}">Ver de novo?</a>